[custom.all.emkit-sourcing]
type = "local"
path = "packages/emkit-sourcing"
ipkg = "emkit-sourcing.ipkg"

[custom.all.emkit-modeling]
type = "local"
path = "packages/emkit-modeling"
ipkg = "emkit-modeling.ipkg"

[custom.all.emkit-stream]
type = "local"
path = "packages/emkit-stream"
ipkg = "emkit-stream.ipkg"

[custom.all.emkit-wire]
type = "local"
path = "packages/emkit-wire"
ipkg = "emkit-wire.ipkg"
